{% set name = "polib" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3ef94aefed6e183e342a8a269ae1fc4742ba193186ad76f175938621dbfc26b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - polib
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://bitbucket.org/izi/polib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library to manipulate gettext files (po and mo files).
  description: |
    * polib allows you to manipulate, create, modify gettext files (pot, po and
      mo files). You can load existing files, iterate through it's entries,
      add, modify entries, comments or metadata, etc... or create new po files
      from scratch.

    * polib supports out of the box any version of python ranging from 2.4 to
    * latest 3.X version.

    * polib is pretty stable now and is used by many opensource projects.
  dev_url: https://bitbucket.org/izi/polib/wiki/Home
  doc_url: https://polib.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - stuertz
    - kcemenike
